OUTPUT: "./_runs/"
VAR_NAME: "aksdb_pf1m_bin"
EXP_NAME: "sat_cov__nogeo__c19"

MODEL:
  DECODER: "visual_geo_dual" 
    
DATA:
  OUT_DIM: 1
  USE_NEIGHBOR_LABELS: False
  USE_OTHER_TILES_RATIO: 0.5
  SAT:
    USE_SAT: True
    NUM_BANDS: 9
  DEM:
    USE_DEM: False
  CLM:
    USE_CLM: False
  COV:
    USE_COV: True
    NUM_BANDS: 10

TRAIN:
  BATCH_SIZE: 32
  BASE_LOSS: "bce"
  EARLY_STOP_CRITERIA: "neg_accuracy"
  AUX_LOSSES: ['visual_geo_nce', 'sat_cov_nce']
  WARMUP_EPOCHS: 30
  RAMPUP_EPOCHS: 40